### ISSUE TITLE
Forgotten Prefix Recovery

### ISSUE THREAD

**Issue by Hwiggy** [TheSourceCodeLLC/Source#15]
I have solved issue #6 and #7, however I have introduced a new problem in doing so.

If a prefix is changed in a guild, and that prefix is then forgotten; there is currently no recovery to reset the prefix to default.
This is a problem because by changing a prefix, the bot can become unusable.

**Comment by TheForbiddenAi** [comment]
Just make it so the bot responds to commands when it is mentioned, so <@!(id)> help
