### ISSUE TITLE
Kotlin Shadowed into Extensions

### ISSUE THREAD

**Issue by Hwiggy** [TheSourceCodeLLC/Source#2]
Currently, Kotlin is making its way into submodules under the `Extensions` module.
Manually excluding Kotlin-related dependencies can mitigate this problem for the most part, with some residual Kotlin classes; seemingly from kotlin-stdlib-jdk8.

We are looking for possible solutions that don't involve the manual exclusion of dependencies in the Extensions submodules tasks.

**Comment by MrIvanPlays** [comment]
return back to maven
